M2-4310: Unit tests for BuilderAppletSettings
ChildMindInstitute/mindlogger-admin pull request #1268
Opened 2023-12-06 10:20 UTC by wildkiomi

2023-12-06 13:04 UTC, nmialik approved these changes

2023-12-07 13:19 UTC, IhorNesterenko99 commented on src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.test.tsx
> +import { BuilderAppletSettings } from './BuilderAppletSettings';
pls add spacing

2023-12-08 13:59 UTC, IhorNesterenko99 approved these changes

2023-12-11 09:23 UTC, alex-i-e commented on src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.test.tsx
> +      ${false}  | ${[Roles.Manager]}  | ${'sharing for Manager'}
what about for the rest roles?

2023-12-11 09:24 UTC, alex-i-e commented on src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.test.tsx
> +    `('$description', ({ isPublished, sectionLabel, items }) => {
could you please add a few tests in case of `isNewApplet=true` ?

2023-12-11 09:26 UTC, alex-i-e commented on src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.test.tsx
> +        roles,
could you please add a few tests with other roles ?

2023-12-11 09:26 UTC, alex-i-e requested changes
left the comments

2023-12-19 08:26 UTC, wildkiomi commented on src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.test.tsx
> +        roles,
it doesn't make sense. because it will return the same. just different isVisible (which is checked in diff tests)

2023-12-19 08:32 UTC, alex-i-e approved these changes

2023-12-19 09:48 UTC, merged