M2-4337: M2-4338: ScheduleSetup and ViewData popups unit tests
ChildMindInstitute/mindlogger-admin pull request #1287
Opened 2023-12-12 10:24 UTC by wildkiomi

2023-12-12 21:15 UTC, alex-i-e requested changes
please add couple of tests to cover useEffect logic

2023-12-13 15:16 UTC, IhorNesterenko99 commented on src/modules/Dashboard/features/Respondents/Popups/ViewDataPopup/ViewDataPopup.test.tsx
> +
pls remove spacing

2023-12-13 15:21 UTC, IhorNesterenko99 approved these changes

2023-12-19 08:41 UTC, alex-i-e approved these changes

2023-12-19 08:53 UTC, merged