feature: Add question text tooltips to Item Flow condition dropdowns (M2-6908)
ChildMindInstitute/mindlogger-admin pull request #1814
Opened 2024-06-18 18:48 UTC by JustinNusca

### 📝 Description

🔗 [M2-6908](https://mindlogger.atlassian.net/browse/M2-6908): [Admin] - Add Tooltip to Item Flow section

This PR updates the Item Flow section of the Activity builder so that dropdowns in the Item flow conditions now show tooltips, which display the question/"Displayed Content" of the selected item in the dropdown.

To do this, I've added a new `ItemFlowSelectController` component, which is a styled variant of the `SelectController`, and wrapped in a `Tooltip` that expects a markdown-formatted string as content, for use in the Condition & SummaryRow components.

As part of this, I've added a styled variant of the `MDPreview` component from our [`md-editor-rt`](https://github.com/imzbf/md-editor-rt) dependency, which removes much of the "themed" styles it otherwise provides.

Finally, I've also updated the `Tooltip` component so that it is styled with a calculated `maxHeight` property that prevents tooltips from extending off of the vertical edges of the viewport. As part of this change, I added an explicit `@popperjs/core` dependency to the project. This was already a transitive dependency via `@mui/core`, which uses Popperjs to implement it's Tooltips already, but I wanted to include specific type annotations that referenced definitions in that package, and wanted to avoid referencing a dependency that was only implicitly included.

Finally, there is a small design update that changes the dropdown inputs in the Condition row, to match the dropdown inputs in the Summary row. This is how this UI is depicted in the designs, and there were existing styles that were intended to implement this, but incorrect selectors previously prevented them from being applied.

### 📸 Screenshots

| Before | After |
|-|-|
| ![before](https://github.com/ChildMindInstitute/mindlogger-admin/assets/1670836/4600ab62-3fe5-4157-b23f-28721b70c124) | ![after](https://github.com/ChildMindInstitute/mindlogger-admin/assets/1670836/3f172469-256b-43ee-a127-202abbfe71e7) |

### 🪤 Peer Testing

For an applet with an activity that contains various items…

1. Navigate to the "Edit Activity" screen, and then to the "Item Flow" tab.
2. Create a new condition, if necessary. Interact with the item dropdowns and observe that they show tooltips containing the rendered markdown content entered in the Item configuration's "Displayed Content" input.

2024-06-18 23:40 UTC, ChaconC approved these changes
Tested a few items and the tooltip is displayed correctly, great work
Minor suggestion but non-blocking

2024-06-18 23:40 UTC, ChaconC commented on src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.tsx
> +    ((items ?? []) as Item[]).find(({ id }) => id === getValues(`${name}.itemKey`)) ?? {};
If you use `ItemFormValues` instead of `Item` we can avoid the `unknown as string` cast below

2024-06-19 01:43 UTC, mbanting requested changes
@JustinNusca I didn't review the PR, but leaving a comment to please merge to `develop` instead of the `feature/multiinformant-metapod` branch. Also noted on the ticket. Thanks!

2024-06-19 14:06 UTC, farmerpaul approved these changes
Looks good! Approving pending @mbanting's request.

2024-06-19 23:13 UTC, mbanting approved these changes
Nice work @JustinNusca !

2024-06-25 16:13 UTC, merged