feat: Add warning if admin has made changes in the 'Edit event' pop-up and closes it with not saving changes (M2-6871)
ChildMindInstitute/mindlogger-admin pull request #1816
Opened 2024-06-19 11:11 UTC by nmialik

- [ ] Tests for the changes have been added
- [ ] Delivered the `fix` or `feature` branches into `develop` or `release` branches via `Squash and Merge` (to keep clean history)

### 📝 Description

🔗 [Jira Ticket M2-6871](https://mindlogger.atlassian.net/browse/M2-6871)

2024-06-19 13:56 UTC, IhorNesterenko99 commented
@nmialik 
Please take a look to a video, it seems in some cases the functionality isn't working properly
https://app.screencast.com/GIBB4EktKErcf

2024-06-20 09:33 UTC, alex-i-e approved these changes

2024-06-20 09:36 UTC, alex-i-e requested changes
There are the event type was changed and could be saved should be fixed

2024-06-20 09:43 UTC, alex-i-e approved these changes

2024-06-20 09:54 UTC, IhorNesterenko99 approved these changes

2024-06-20 21:28 UTC, merged